
day_color_plate = c("#5E4FA2", "#515FA9", "#446FB1", "#387FB9", "#3990B9", "#48A0B2", "#57B1AB",
                    "#65C2A5", "#79C9A4", "#8DD1A4", "#A1D9A4", "#B3E0A2", "#C4E79E", "#D5EE9B",
                    "#E5F498", "#EDF7A3", "#F4FAAE", "#FBFDB9", "#FEFAB7", "#FEF1A8", "#FEE899",
                    "#FEE08B", "#FDD17F", "#FDC373", "#FDB567", "#FBA45C", "#F99254", "#F67F4B",
                    "#F46D43", "#EB5F46", "#E25249", "#D9444D", "#CD354D", "#BD2349", "#AD1245", "#9E0142")
day_list = c("E10.0", "E10.25", "E10.5", "E10.75", "E11.0", "E11.25", "E11.5",
             "E11.75", "E12.0", "E12.25", "E12.5", "E12.75", "E13.0", "E13.25",
             "E13.5", "E13.75", "E14.0", "E14.25", "E14.375", "E14.75", "E15.0",
             "E15.25", "E15.5", "E15.75", "E16.0", "E16.25", "E16.5", "E16.75",
             "E17.0", "E17.25", "E17.5", "E18.0", "E18.25", "E18.5", "E18.75", "P0")
names(day_color_plate) = day_list

t1 = list(family = 'Helvetica',
          size = 25,
          color = "black")
t2 = list(family = 'Helvetica',
          size = 15,
          color = "grey")

celltype_L1_color_plate = c("Neuroectoderm" = "#f96100",
                            "Mesoderm" = "#bb46c5",
                            "Epithelial_cells" = "#af9fb6",
                            "Erythroid_cells" = "#dc453e",
                            "Muscle_cells" = "#ffa1f5",
                            "White_blood_cells" = "#7ca0ff",
                            "Hepatocytes" = "#185700",
                            "Endothelium" = "#00a34e",
                            "NMPs_and_spinal_cord_progenitors" = "#cf6a79",
                            "Adipocytes" = "#5e7fbf",
                            "Neural_crest_PNS_glia" = "#fff167",
                            "Olfactory_sensory_neurons" = "#e6230b",
                            "Oligodendrocytes" = "#916e00")

celltype_L2_color_plate = c("Adipocyte_cells_Cyp2e1_L2" = "#7f3e39",
                            "Adipocyte_cells_L2" = "#5e7fbf",
                            "Brain_capillary_endothelial_cells_L2" = "#b25525",
                            "Endocardial_cells_L2" = "#c6a851",
                            "Endothelium_L2" = "#00a34e",
                            "Glomerular_endothelial_cells_L2" = "#7a66d6",
                            "Liver_sinusoidal_endothelial_cells_L2" = "#748132",
                            "Lymphatic_vessel_endothelial_cells_L2" = "#ca47a7",
                            "Epithelial_cells_L2" = "#af9fb6",
                            "Gut_epithelial_cells_L2" = "#ff007a",
                            "Kidney_L2" = "#65c17d",
                            "Lung_and_airway_L2" = "#02b0d1",
                            "Definitive_erythroid_L2" = "#dc453e",
                            "Erythroid_progenitors_L2" = "#cc3f74",
                            "Primitive_erythroid_L2" = "#ffa9a1",
                            "Hepatocytes_L2" = "#185700",
                            "Lateral_plate_and_intermediate_mesoderm_L2" = "#d78860",
                            "Mesoderm_L2" = "#bb46c5",
                            "Cardiomyocytes_L2" = "#643e8c",
                            "Skeletal_muscle_cells_L2" = "#ffa1f5",
                            "NMPs_and_spinal_cord_progenitors_L2" = "#cf6a79",
                            "Melanocyte_cells_L2" = "#88b439",
                            "Neural_crest_PNS_glia_L2" = "#fff167",
                            "Olfactory_ensheathing_cells_L2" = "#b46aa2",
                            "CNS_neurons_L2" = "#e5c000",
                            "Eye_L2" = "#00d450",
                            "Intermediate_neuronal_progenitors_L2" = "#2e0ab7",
                            "Neural_crest_PNS_neurons_L2" = "#b5ce92",
                            "Neuroectoderm_and_glia_L2" = "#f96100",
                            "Corticofugal_neurons_L2" = "#8d6a32",
                            "Olfactory_sensory_neurons_L2" = "#e6230b",
                            "Committed_oligodendrocyte_precursors_L2" = "#408352",
                            "Oligodendrocyte_progenitor_cells_L2" = "#916e00",
                            "B_cells_L2" = "#01b7a6",
                            "T_cells_L2" = "#ff9d47",
                            "White_blood_cells_L2" = "#7ca0ff")

window_cluster_color_plate = c("Adipocyte_cells_Cyp2e1" = "#7f3e39",
                               "Adipocyte_cells" = "#5e7fbf",
                               "Brain_capillary_endothelial_cells" = "#b25525",
                               "Endocardial_cells" = "#c6a851",
                               "Endothelium" = "#00a34e",
                               "Glomerular_endothelial_cells" = "#7a66d6",
                               "Liver_sinusoidal_endothelial_cells" = "#748132",
                               "Lymphatic_vessel_endothelial_cells" = "#ca47a7",
                               "Epithelial_cells" = "#af9fb6",
                               "Gut_epithelial_cells" = "#ff007a",
                               "Kidney" = "#65c17d",
                               "Lung_and_airway" = "#02b0d1",
                               "Erythroid_cells" = "#dc453e",
                               "Hepatocytes" = "#185700",
                               "Lateral_plate_and_intermediate_mesoderm" = "#d78860",
                               "Mesoderm" = "#bb46c5",
                               "Cardiomyocytes" = "#643e8c",
                               "Skeletal_muscle_cells" = "#ffa1f5",
                               "Promoters" = "grey80",
                               "Melanocyte_cells" = "#88b439",
                               "Glia" = "#fff167",
                               "Olfactory_ensheathing_cells" = "#b46aa2",
                               "CNS_neurons" = "#e5c000",
                               "Eye" = "#00d450",
                               "Intermediate_neuronal_progenitors" = "#2e0ab7",
                               "Neural_crest_PNS_neurons" = "#b5ce92",
                               "Neuroectoderm_and_glia" = "#f96100",
                               "Corticofugal_neurons" = "#8d6a32",
                               "Olfactory_neurons" = "#e6230b",
                               "Oligodendrocytes" = "#916e00",
                               "B_cells" = "#01b7a6",
                               "T_cells" = "#ff9d47",
                               "White_blood_cells" = "#7ca0ff")


